### ISSUE TITLE
Tawny

### ISSUE THREAD

**Issue by phillord** [ozekik/awesome-ontology#4]
Thought you might be interested to add tawny-owl https://github.com/phillord/tawny-owl.

It's either an editor, utility or library depending on your point of view. Or all three.

**Comment by ozekik** [comment]
Thank you for your suggestion! I appreciate it and would be happy to include it. If possible, could you please create a pull request to clarify your contribution for this? Adding it to [the programming section](https://github.com/ozekik/awesome-ontology#programming) would be a great choice.

**Comment by ozekik** [comment]
Added by [5b2aecd](https://github.com/ozekik/awesome-ontology/commit/5b2aecdbe28d989b342279aad9f16a767ed7a35e). Thanks!
